In [ ]:
#código para comprobar distintos dataset con modelos semi-supervisados

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.semi_supervised import SelfTrainingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
#carga del dataset iris

In [ ]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
#lista con los % de etiquetas a eliminar

In [ ]:
listaPorcentajes = [0.1,0.3,0.6,0.9]

In [ ]:
#código para eliminar parte de los datos y comprobar los resultados de los mismos

In [ ]:
for i in listaPorcentajes:
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)#cargo el dataset en las variables
  print(("number of instances -> " + str(X_train.shape[0])))#instancias
  print(("number of attributes -> " + str(X_train.shape[1])))#atributos
  print("\n")

  #código para eliminar % de datos
  rng = np.random.RandomState(42)
  random_unlabeled_points = rng.rand(y_train.shape[0]) < i
  y_train[random_unlabeled_points] = -1
  y_train_sin_patrones = list(filter(lambda x: x != -1,y_train))
  x_train_sin_patrones = []
  for w in range(len(X_train)):
    if not random_unlabeled_points[w]:
      x_train_sin_patrones.append(X_train[w])
  #modelo de autoentrenamiento
#-----------------------------------------------------
  svc = SVC(probability=True, gamma="auto")
  self_training_model = SelfTrainingClassifier(svc)
  self_training_model.fit(X_train, y_train)
  #resultados obtenidos de dicho modelo
  pred = self_training_model.predict(X_test)
  cm = confusion_matrix(y_test,pred)
  print("Matriz de confusión para", i, "aplicando semi-supervisado")
  print(cm)
  print("Accuracy score ->", accuracy_score(y_test, pred))
  print("\n")
#-----------------------------------------------------
  svc = SVC(probability=True, gamma="auto")
  svc.fit(x_train_sin_patrones, y_train_sin_patrones)
  #resultados obtenidos de dicho modelo
  pred = self_training_model.predict(X_test)
  cm = confusion_matrix(y_test,pred)
  print("Matriz de confusión para", i, "eliminando los datos sin etiqueta")
  print(cm)
  print("Accuracy score ->", accuracy_score(y_test, pred))
  print("\n")

number of instances -> 100
number of attributes -> 4


Matriz de confusión para 0.1 aplicando semi-supervisado
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
Accuracy score -> 1.0


Matriz de confusión para 0.1 eliminando los datos sin etiqueta
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
Accuracy score -> 1.0


number of instances -> 100
number of attributes -> 4


Matriz de confusión para 0.3 aplicando semi-supervisado
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
Accuracy score -> 1.0


Matriz de confusión para 0.3 eliminando los datos sin etiqueta
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
Accuracy score -> 1.0


number of instances -> 100
number of attributes -> 4


Matriz de confusión para 0.6 aplicando semi-supervisado
[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
Accuracy score -> 0.98


Matriz de confusión para 0.6 eliminando los datos sin etiqueta
[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
Accuracy score -> 0.98


number of instances -> 100
number of attributes -> 4


Matriz de confusión para 0.9 aplicando semi-supervisado

In [ ]:
#se realiza la misma prueba para el dataset winw

In [ ]:
wine = datasets.load_wine()
X = wine.data
y = wine.target

In [ ]:
#lista con los % de etiquetas a eliminar

In [ ]:
listaPorcentajes = [0.1,0.3,0.6,0.9]

In [ ]:
#código para eliminar parte de los datos y comprobar los resultados de los mismos

In [ ]:
for i in listaPorcentajes:
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)#cargo el dataset en las variables
  print(("number of instances -> " + str(X_train.shape[0])))#instancias
  print(("number of attributes -> " + str(X_train.shape[1])))#atributos
  print("\n")

  #código para eliminar % de datos
  rng = np.random.RandomState(42)
  random_unlabeled_points = rng.rand(y_train.shape[0]) < i
  y_train[random_unlabeled_points] = -1
  y_train_sin_patrones = list(filter(lambda x: x != -1,y_train))
  x_train_sin_patrones = []
  for w in range(len(X_train)):
    if not random_unlabeled_points[w]:
      x_train_sin_patrones.append(X_train[w])
  #modelo de autoentrenamiento
#-----------------------------------------------------
  svc = SVC(probability=True, gamma="auto")
  self_training_model = SelfTrainingClassifier(svc)
  self_training_model.fit(X_train, y_train)
  #resultados obtenidos de dicho modelo
  pred = self_training_model.predict(X_test)
  cm = confusion_matrix(y_test,pred)
  print("Matriz de confusión para", i, "aplicando semi-supervisado")
  print(cm)
  print("Accuracy score ->", accuracy_score(y_test, pred))
  print("\n")
#-----------------------------------------------------
  svc = SVC(probability=True, gamma="auto")
  svc.fit(x_train_sin_patrones, y_train_sin_patrones)
  #resultados obtenidos de dicho modelo
  pred = self_training_model.predict(X_test)
  cm = confusion_matrix(y_test,pred)
  print("Matriz de confusión para", i, "eliminando los datos sin etiqueta")
  print(cm)
  print("Accuracy score ->", accuracy_score(y_test, pred))
  print("\n")

number of instances -> 119
number of attributes -> 13


Matriz de confusión para 0.1 aplicando semi-supervisado
[[ 1 19  0]
 [ 0 24  0]
 [ 0 15  0]]
Accuracy score -> 0.423728813559322


Matriz de confusión para 0.1 eliminando los datos sin etiqueta
[[ 1 19  0]
 [ 0 24  0]
 [ 0 15  0]]
Accuracy score -> 0.423728813559322


number of instances -> 119
number of attributes -> 13


Matriz de confusión para 0.3 aplicando semi-supervisado
[[ 1 19  0]
 [ 0 24  0]
 [ 0 15  0]]
Accuracy score -> 0.423728813559322


Matriz de confusión para 0.3 eliminando los datos sin etiqueta
[[ 1 19  0]
 [ 0 24  0]
 [ 0 15  0]]
Accuracy score -> 0.423728813559322


number of instances -> 119
number of attributes -> 13


Matriz de confusión para 0.6 aplicando semi-supervisado
[[ 1 19  0]
 [ 0 24  0]
 [ 0 15  0]]
Accuracy score -> 0.423728813559322


Matriz de confusión para 0.6 eliminando los datos sin etiqueta
[[ 1 19  0]
 [ 0 24  0]
 [ 0 15  0]]
Accuracy score -> 0.423728813559322


number of instances -> 11

In [ ]:
#se realiza la misma prueba para un dataset moons

In [ ]:
from sklearn.datasets import make_moons
X, y = make_moons(n_samples=20000, noise=0.5, random_state=42)

In [ ]:
#lista con los % de etiquetas a eliminar

In [ ]:
listaPorcentajes = [0.1,0.3,0.6,0.9]

In [ ]:
#código para eliminar parte de los datos y comprobar los resultados de los mismos

In [ ]:
for i in listaPorcentajes:
  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)#cargo el dataset en las variables
  print(("number of instances -> " + str(X_train.shape[0])))#instancias
  print(("number of attributes -> " + str(X_train.shape[1])))#atributos
  print("\n")

  #código para eliminar % de datos
  rng = np.random.RandomState(42)
  random_unlabeled_points = rng.rand(y_train.shape[0]) < i
  y_train[random_unlabeled_points] = -1
  y_train_sin_patrones = list(filter(lambda x: x != -1,y_train))
  x_train_sin_patrones = []
  for w in range(len(X_train)):
    if not random_unlabeled_points[w]:
      x_train_sin_patrones.append(X_train[w])
  #modelo de autoentrenamiento
#-----------------------------------------------------
  svc = SVC(probability=True, gamma="auto")
  self_training_model = SelfTrainingClassifier(svc)
  self_training_model.fit(X_train, y_train)
  #resultados obtenidos de dicho modelo
  pred = self_training_model.predict(X_test)
  cm = confusion_matrix(y_test,pred)
  print("Matriz de confusión para", i, "aplicando semi-supervisado")
  print(cm)
  print("Accuracy score ->", accuracy_score(y_test, pred))
  print("\n")
#-----------------------------------------------------
  svc = SVC(probability=True, gamma="auto")
  svc.fit(x_train_sin_patrones, y_train_sin_patrones)
  #resultados obtenidos de dicho modelo
  pred = self_training_model.predict(X_test)
  cm = confusion_matrix(y_test,pred)
  print("Matriz de confusión para", i, "eliminando los datos sin etiqueta")
  print(cm)
  print("Accuracy score ->", accuracy_score(y_test, pred))
  print("\n")

number of instances -> 13400
number of attributes -> 2


Matriz de confusión para 0.1 aplicando semi-supervisado
[[2774  597]
 [ 548 2681]]
Accuracy score -> 0.8265151515151515


Matriz de confusión para 0.1 eliminando los datos sin etiqueta
[[2774  597]
 [ 548 2681]]
Accuracy score -> 0.8265151515151515


number of instances -> 13400
number of attributes -> 2


Matriz de confusión para 0.3 aplicando semi-supervisado
[[2776  595]
 [ 549 2680]]
Accuracy score -> 0.8266666666666667


Matriz de confusión para 0.3 eliminando los datos sin etiqueta
[[2776  595]
 [ 549 2680]]
Accuracy score -> 0.8266666666666667


number of instances -> 13400
number of attributes -> 2


Matriz de confusión para 0.6 aplicando semi-supervisado
[[2798  573]
 [ 577 2652]]
Accuracy score -> 0.8257575757575758


Matriz de confusión para 0.6 eliminando los datos sin etiqueta
[[2798  573]
 [ 577 2652]]
Accuracy score -> 0.8257575757575758


number of instances -> 13400
number of attributes -> 2


Matriz de confusión